name = "ultimate_ladder"
id = "ultimate_ladder"
packaging_format = 1
version = "0.2~ynh1"
url = "https://github.com/trahay/ultimate_ladder_ynh"
license = "MIT"
previous_maintainers = [ ]
multi_instance = false
services = [ "nginx", "postgresql", "redis" ]

[description]
en = "A matchmaking website for creating balanced teams when playing ultimate frisbee."

[upstream]
license = "MIT"
website = "https://github.com/trahay/ultimate-ladder/"
code = "https://github.com/trahay/ultimate-ladder/"

[maintainer]
name = "François Trahay"
email = "ftrahay@gmail.com"

[requirements]
yunohost = ">= 4.4"

[arguments]

  [[arguments.install]]
  name = "domain"
  type = "domain"
  
  [[arguments.install]]
  name = "path"
  type = "path"
  example = "/ultimate_ladder"
  default = "/ultimate_ladder"
  
  [[arguments.install]]
  name = "admin"
  type = "user"

[resources]

    [resources.sources]

        [resources.sources.main]
	url="https://github.com/trahay/ultimate-ladder/archive/refs/tags/0.4.tar.gz"
	sha256="92f19d5cd437544d6dab3815a35d15452d9b08f0f3bccfb32b5e69db8cf1a918"
	
	