# Generated by Django 5.0.1 on 2024-01-29 15:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('m', 'M'), ('f', 'F')], max_length=10)),
                ('score', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('completed', models.BooleanField(default=False)),
                ('score_team_a', models.IntegerField(default=0)),
                ('score_team_b', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimate_ladder.league')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimate_ladder.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimate_ladder.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimate_ladder.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimate_ladder.player')),
            ],
        ),
    ]
